### ISSUE TITLE
Cannot find module 'debug'

### ISSUE THREAD

**Issue by samuelpatro** [mongodb-js/electron-squirrel-startup#27]

**Comment by anuprajg** [comment]
Is this somehow resolved ?

**Comment by samuelpatro** [comment]
I think no

**Comment by anuprajg** [comment]
Got it working by removing all the Debug statements from the code...

**Comment by samuelpatro** [comment]
I created switch with squirrel args, its same but any depedencies dont needed

**Comment by mblundred-yseop** [comment]
I'm having this problem too when using squirrel-winstaller to generate a .exe setup file.

The debug package version ^2.2.0 has been correctly packaged inside my node_modules/ folder in the AppData directory, but when running my application I get the following error:

![image](https://cloud.githubusercontent.com/assets/20681831/24398198/f8424e54-13a8-11e7-9fdf-1ae4e4baa63d.png)

Annoyingly I can't expand the error box, but I'm pretty sure the problem is encountered at line 3 of index.js

> var debug = require('debug')('electron-squirrel-startup');

I have had this problem intermittently, I'll try to remember to post in this ticket if I figure out precisely what the problem is or how to replicate it.

----

**EDIT**

Figured it out! So I'm packaging an Angular 2 application and I configured electron-packager to ignore both my  quark/electron/releases/ directory and the quark/src/ directory (quark is just what I've called my app). If I don't package the source code I can replicate this error, and it's fixed when reincluding it.
The debug module's package.json compiled in the AppData folder has its **main** and **browser** options set to **./src/main.js** and **./src/browser.js** respectively. This caused electron-squirrel-startup's dependency to the debug package to break when not including the src/ directory when using electron-packager.

**Comment by roman0x58** [comment]
I think the debug dependency should be removed, because the script used in the final app, and many users don't wanna attach all dependencies from node_modules

**Comment by matthewtmoran** [comment]
Any progress on this issue?  Extremely frustrating.

**Comment by CommanderGL** [comment]
you have to edit .npmrc to look like
```properties
node-linker=hoisted
public-hoist-pattern=*
shamefully-hoist=true
```

**Comment by bbugh** [comment]
I landed here from a web search. I was having this issue because the project uses `pnpm` and whatever module is trying to be resolved here does not seem to support the virtual paths that pnpm uses.
