### ISSUE TITLE
Debug Documentation?

### ISSUE THREAD

**Issue by razzeee** [mongodb-js/electron-squirrel-startup#6]
Hey there,

pretty new with electron and node.js, is there a way to debug the squirrel events?
I'm especially trying to find out why '--squirrel-uninstall' doesn't seem to happen for me.

Thanks

**Comment by imlucas** [comment]
Hey @Razzeee,

This module uses the debug module which might be helpful for you.  Usage docs can be found [here](https://github.com/visionmedia/debug#windows-note).

Debugging in the main process of electron (where electron-squirrel-startup runs) is notoriously difficult.  However, the electron docs provide a nice solution to this (rather than trying to fuss with the debug module): https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process.md

Please feel free to reopen this issue if the above is unclear or you find a good solution specific to squirrel debugging as I'm sure many others would be interested as well.

Thanks,
Lucas
